### ISSUE TITLE
记录2023-06-13交流群反馈配置注入集合问题

### ISSUE THREAD

**Issue by dragon-dan** [noear/solon#164]
pom文件引入：
<dependency>
    <groupId>org.noear</groupId>
    <artifactId>solon-web</artifactId>
</dependency>

solon版本：2.3.0

【失败】
（1）@Inject后写上默认值列表，启动注入失败：
@Inject("${upload.img.ext:png,jpg}")
private Set<String> upImgExtSet; // 换成List<String>， String[] 也都失败

（2）@Inject默认值只保留一个，启动注入失败：
@Inject("${upload.img.ext:png}")
private Set<String> upImgExtSet; // 换成List<String>， String[] 也都失败

（3）@Inject后不使用默认值，把配置放到配置文件，启动注入失败：
@Inject("${upload.img.ext}")
private Set<String> upImgExtSet; // 换成List<String>， String[] 也都失败

【成功】
@Inject("${upload.img.ext}")
private String upImgExtSet; // 配置放到配置文件里，String可以接收，然后自行切割

期望 Set<String>，List<String>， String[]这些集合写法都能注入，@Inject后默认值列表也可以注入。

**Comment by noear** [comment]
你的配置 “upload.img.ext” 值是什么？

**Comment by dragon-dan** [comment]
和spring配置读取到集合的写法一样，如：png,jpg
逗号分割的字符串。

短横线开头的换行写法如：
```
upload:
  img:
    ext:
      - png
      - jpg
```
还没尝试

**Comment by noear** [comment]
```yaml
upload:
  img:
    ext:
      - png
      - jpg
```

这个格式是可以的。
